# Generated by Django 3.0.4 on 2020-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200316_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cena',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='rok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
