# Generated by Django 3.0.4 on 2020-03-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200318_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stan',
            field=models.CharField(blank=True, choices=[('Z kierowcą', 'Z kierowcą'), ('Bez kierowcy', 'Bez kierowcy'), ('Stojący w miejscu', 'Stojący w miejscu')], default=None, max_length=30, null=True, verbose_name='Stan'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cena',
            field=models.FloatField(default=0, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='Kolor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rok',
            field=models.IntegerField(default=0, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='index',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
    ]
