# Generated by Django 3.0.4 on 2020-03-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200318_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image4',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image5',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='stan',
            field=models.CharField(blank=True, choices=[('Z kierowcą', 'Z kierowcą'), ('Bez kierowcy', 'Bez kierowcy'), ('Stojący w miejscu', 'Stojący w miejscu')], default='Brak informacji', max_length=30, null=True, verbose_name='Stan'),
        ),
    ]
