# Generated by Django 3.0.4 on 2020-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200319_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='cena',
        ),
        migrations.AlterField(
            model_name='car',
            name='stan',
            field=models.CharField(blank=True, choices=[('Z kierowcą', 'Jeżdzący'), ('Bez kierowcy', 'Stojący'), ('Stojący w miejscu', 'Z kierowcą')], default='Brak informacji', max_length=30, null=True, verbose_name='Stan'),
        ),
    ]
