# Generated by Django 3.0.4 on 2020-03-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200328_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Car')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_cars',
            field=models.ManyToManyField(through='catalog.OrderedCar', to='catalog.Car'),
        ),
    ]
