# Generated by Django 3.0.4 on 2020-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='description',
        ),
        migrations.AddField(
            model_name='index',
            name='description1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description10',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description3',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description4',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description5',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description6',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description7',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description8',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='index',
            name='description9',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
    ]
